In [1]:
import pandas as pd

employees = {
   "Employee_ID": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
   "Employee_Name": [
      "Amit", "Neha", "Rahul", "Priya", "Rohan",
      "Sneha", "Karan", "Anjali", "Vikram", "Pooja"
   ],
   "Department": [
      "HR", "IT", "Finance", "Marketing", "Sales",
      "Operations", "IT", "Finance", "HR", "Sales"
   ],
   "Salary": [
      35000, 45000, 50000, 40000, 38000,
      42000, 55000, 48000, 36000, 41000
   ]
}

df = pd.DataFrame(employees)

df.to_csv("../data/employees.csv", index=False)

df

   Employee_ID Employee_Name  Department  Salary
0          201          Amit          HR   35000
1          202          Neha          IT   45000
2          203         Rahul     Finance   50000
3          204         Priya   Marketing   40000
4          205         Rohan       Sales   38000
5          206         Sneha  Operations   42000
6          207         Karan          IT   55000
7          208        Anjali     Finance   48000
8          209        Vikram          HR   36000
9          210         Pooja       Sales   41000

In [3]:
print("Number of employees:", len(df))
print("Dataset shape:", df.shape)

Number of employees: 10
Dataset shape: (10, 4)

In [4]:
df["Salary"] = df["Salary"] * 1.10
df.to_csv("../data/employees.csv", index=False)

df

   Employee_ID Employee_Name  Department   Salary
0          201          Amit          HR  38500.0
1          202          Neha          IT  49500.0
2          203         Rahul     Finance  55000.0
3          204         Priya   Marketing  44000.0
4          205         Rohan       Sales  41800.0
5          206         Sneha  Operations  46200.0
6          207         Karan          IT  60500.0
7          208        Anjali     Finance  52800.0
8          209        Vikram          HR  39600.0
9          210         Pooja       Sales  45100.0

In [5]:
print("Number of employees:", len(df))
print("Average salary:", df["Salary"].mean())

Number of employees: 10
Average salary: 47300.0

In [6]:
df["Years_of_Experience"] = [2, 4, 5, 3, 2, 6, 7, 5, 3, 4]

df.to_csv("../data/employees.csv", index=False)

df

   Employee_ID Employee_Name  Department   Salary  Years_of_Experience
0          201          Amit          HR  38500.0                    2
1          202          Neha          IT  49500.0                    4
2          203         Rahul     Finance  55000.0                    5
3          204         Priya   Marketing  44000.0                    3
4          205         Rohan       Sales  41800.0                    2
5          206         Sneha  Operations  46200.0                    6
6          207         Karan          IT  60500.0                    7
7          208        Anjali     Finance  52800.0                    5
8          209        Vikram          HR  39600.0                    3
9          210         Pooja       Sales  45100.0                    4

In [7]:
print("Columns:", list(df.columns))
print("Dataset shape:", df.shape)

Columns: ['Employee_ID', 'Employee_Name', 'Department', 'Salary', 'Years_of_Experience']
Dataset shape: (10, 5)

In [8]:
df["Performance_Rating"] = [
    "Excellent",
    "Very Good",
    "Good",
    "Excellent",
    "Average",
    "Very Good",
    "Excellent",
    "Good",
    "Average",
    "Very Good"
]

df.to_csv("../data/employees.csv", index=False)

df

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Amit,HR,38500.0,2,Excellent
1,202,Neha,IT,49500.0,4,Very Good
2,203,Rahul,Finance,55000.0,5,Good
3,204,Priya,Marketing,44000.0,3,Excellent
4,205,Rohan,Sales,41800.0,2,Average
5,206,Sneha,Operations,46200.0,6,Very Good
6,207,Karan,IT,60500.0,7,Excellent
7,208,Anjali,Finance,52800.0,5,Good
8,209,Vikram,HR,39600.0,3,Average
9,210,Pooja,Sales,45100.0,4,Very Good

In [9]:
print("Columns:", list(df.columns))
print("Dataset shape:", df.shape)

Columns: ['Employee_ID', 'Employee_Name', 'Department', 'Salary', 'Years_of_Experience', 'Performance_Rating']
Dataset shape: (10, 6)

In [10]:
new_employees = pd.DataFrame({
    "Employee_ID": [211, 212, 213],
    "Employee_Name": ["Arjun", "Meera", "Sahil"],
    "Department": ["IT", "Marketing", "Operations"],
    "Salary": [52000, 46000, 43000],
    "Years_of_Experience": [5, 3, 4],
    "Performance_Rating": ["Excellent", "Good", "Very Good"]
})

df = pd.concat([df, new_employees], ignore_index=True)

df.to_csv("../data/employees.csv", index=False)

df

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Amit,HR,38500.0,2,Excellent
1,202,Neha,IT,49500.0,4,Very Good
2,203,Rahul,Finance,55000.0,5,Good
3,204,Priya,Marketing,44000.0,3,Excellent
4,205,Rohan,Sales,41800.0,2,Average
5,206,Sneha,Operations,46200.0,6,Very Good
6,207,Karan,IT,60500.0,7,Excellent
7,208,Anjali,Finance,52800.0,5,Good
8,209,Vikram,HR,39600.0,3,Average
9,210,Pooja,Sales,45100.0,4,Very Good
10,211,Arjun,IT,52000.0,5,Excellent
11,212,Meera,Marketing,46000.0,3,Good
12,213,Sahil,Operations,43000.0,4,Very Good

In [11]:
print("Number of employees:", len(df))
print("Dataset shape:", df.shape)

Number of employees: 13
Dataset shape: (13, 6)

In [12]:
department_mapping = {
    "HR": "Human Resources",
    "IT": "Engineering",
    "Finance": "Accounts & Finance",
    "Marketing": "Business Development",
    "Sales": "Sales & Marketing",
    "Operations": "Business Operations"
}

df["Department"] = df["Department"].replace(department_mapping)

df.to_csv("../data/employees.csv", index=False)

df

,Employee_ID,Employee_Name,Department,Salary,Years_of_Experience,Performance_Rating
0,201,Amit,Human Resources,38500.0,2,Excellent
1,202,Neha,Engineering,49500.0,4,Very Good
2,203,Rahul,Accounts & Finance,55000.0,5,Good
3,204,Priya,Business Development,44000.0,3,Excellent
4,205,Rohan,Sales & Marketing,41800.0,2,Average
5,206,Sneha,Business Operations,46200.0,6,Very Good
6,207,Karan,Engineering,60500.0,7,Excellent
7,208,Anjali,Accounts & Finance,52800.0,5,Good
8,209,Vikram,Human Resources,39600.0,3,Average
9,210,Pooja,Sales & Marketing,45100.0,4,Very Good
10,211,Arjun,Engineering,52000.0,5,Excellent
11,212,Meera,Business Development,46000.0,3,Good
12,213,Sahil,Business Operations,43000.0,4,Very Good

In [13]:
print(df["Department"].unique())
print("Dataset shape:", df.shape)

<StringArray>
[     'Human Resources',          'Engineering',   'Accounts & Finance',
 'Business Development',    'Sales & Marketing',  'Business Operations']
Length: 6, dtype: str
Dataset shape: (13, 6)