In [1]:
import pandas as pd

employees = {
   "Employee_ID": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
   "Employee_Name": [
      "Amit", "Neha", "Rahul", "Priya", "Rohan",
      "Sneha", "Karan", "Anjali", "Vikram", "Pooja"
   ],
   "Department": [
      "HR", "IT", "Finance", "Marketing", "Sales",
      "Operations", "IT", "Finance", "HR", "Sales"
   ],
   "Salary": [
      35000, 45000, 50000, 40000, 38000,
      42000, 55000, 48000, 36000, 41000
   ]
}

df = pd.DataFrame(employees)

df.to_csv("../data/employees.csv", index=False)

df

   Employee_ID Employee_Name  Department  Salary
0          201          Amit          HR   35000
1          202          Neha          IT   45000
2          203         Rahul     Finance   50000
3          204         Priya   Marketing   40000
4          205         Rohan       Sales   38000
5          206         Sneha  Operations   42000
6          207         Karan          IT   55000
7          208        Anjali     Finance   48000
8          209        Vikram          HR   36000
9          210         Pooja       Sales   41000

In [3]:
print("Number of employees:", len(df))
print("Dataset shape:", df.shape)

Number of employees: 10
Dataset shape: (10, 4)

In [4]:
df["Salary"] = df["Salary"] * 1.10
df.to_csv("../data/employees.csv", index=False)

df

   Employee_ID Employee_Name  Department   Salary
0          201          Amit          HR  38500.0
1          202          Neha          IT  49500.0
2          203         Rahul     Finance  55000.0
3          204         Priya   Marketing  44000.0
4          205         Rohan       Sales  41800.0
5          206         Sneha  Operations  46200.0
6          207         Karan          IT  60500.0
7          208        Anjali     Finance  52800.0
8          209        Vikram          HR  39600.0
9          210         Pooja       Sales  45100.0

In [5]:
print("Number of employees:", len(df))
print("Average salary:", df["Salary"].mean())

Number of employees: 10
Average salary: 47300.0